Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -102,7 +102,7 @@ jobs:
       - name: Health Check
         run: |
           echo "Checking service health on port $APP_PORT..."
-          curl --fail http://localhost:$APP_PORT/health || (echo "Health check failed!" && exit 1)
+          curl --fail http://localhost:${{ env.APP_PORT }}/health || (echo "Health check failed!" && exit 1)
  
       # --- CLEANUP BUILD DIRECTORY ---
       - name: Cleanup Build Directory
